/**
 * Template catalog. A template = a layout + a look. Templates never contain
 * the user's content, so switching is always safe.
 */
import type { Block, Design, IconShape, ImageShape, SignatureDoc } from "./types";
import { MG_SPECS, MODERN_SPECS } from "./blockTemplates";
import { DEFAULT_DESIGN } from "./defaults";

export type LayoutId =
  | "classic"
  | "stacked"
  | "centered"
  | "banner"
  | "sidebar"
  | "card"
  | "split3"
  | "compact"
  | "editorial"
  | "monogram"
  | "photoRight"
  | "grid"
  | "bold"
  | "chips";

export type TemplateGroup = "Business" | "Artistic" | "Modern" | "Modern Gentlemen";

/** A layout built from builder blocks — for designs the fixed layouts can't express. */
export type BlockRecipe = (doc: SignatureDoc) => Block[];

export interface Template {
  id: string;
  name: string;
  group: TemplateGroup;
  category: string;
  description: string;
  layout: LayoutId;
  design: Design;
  photo: { shape: ImageShape; size: number };
  logo: { size: number };
  /** When set, the template opens as a builder layout made of these blocks. */
  blocks?: BlockRecipe;
}

export interface Spec {
  id: string;
  name: string;
  group: TemplateGroup;
  category: string;
  description: string;
  layout: LayoutId;
  design?: Partial<Omit<Design, "social">> & { social?: Partial<Design["social"]> };
  photo?: { shape?: ImageShape; size?: number };
  logo?: { size?: number };
  blocks?: BlockRecipe;
}

export const icon = (shape: IconShape, colorMode: Design["social"]["colorMode"] = "accent", size = 22) => ({ shape, colorMode, size });

const SPECS: Spec[] = [
  // ── Business sectors ──────────────────────────────────────────────────────
  {
    id: "corporate-classic",
    name: "Corporate Classic",
    group: "Business",
    category: "Corporate",
    description: "Photo, clean details and a fine divider.",
    layout: "classic",
    design: { accent: "#1f4fd1", text: "#16213a", muted: "#5d6782", headingFont: "helvetica", bodyFont: "helvetica", social: icon("circle") },
  },
  {
    id: "corporate-boardroom",
    name: "Boardroom",
    group: "Business",
    category: "Corporate",
    description: "Three columns with logo and social on the right.",
    layout: "split3",
    design: {
      accent: "#0f2a4a",
      text: "#0f2a4a",
      muted: "#5b6a7d",
      headingFont: "georgia",
      bodyFont: "helvetica",
      contactIcons: "letters",
      social: icon("square", "accent", 20),
    },
  },
  {
    id: "realestate-keys",
    name: "Keys",
    group: "Business",
    category: "Real estate",
    description: "Bold agent photo, chunky icons and a CTA.",
    layout: "bold",
    design: { accent: "#c8102e", text: "#1b1b1b", muted: "#666666", headingFont: "montserrat", bodyFont: "helvetica", social: icon("rounded") },
    photo: { shape: "rounded", size: 96 },
  },
  {
    id: "realestate-estate",
    name: "Estate",
    group: "Business",
    category: "Real estate",
    description: "Brokerage banner header with your details below.",
    layout: "banner",
    design: { accent: "#1d4d3a", text: "#1d2a24", muted: "#5d6b64", headingFont: "playfair", bodyFont: "georgia", social: icon("circle") },
  },
  {
    id: "legal-counsel",
    name: "Counsel",
    group: "Business",
    category: "Legal",
    description: "Restrained serif with lettered contacts.",
    layout: "stacked",
    design: {
      accent: "#3d2b1f",
      text: "#231a14",
      muted: "#6f6259",
      headingFont: "libre-baskerville",
      bodyFont: "georgia",
      contactIcons: "letters",
      divider: "line",
      social: icon("plain", "mono", 16),
    },
  },
  {
    id: "legal-partner",
    name: "Partner",
    group: "Business",
    category: "Legal",
    description: "A navy sidebar rule and a quiet layout.",
    layout: "sidebar",
    design: {
      accent: "#14274e",
      text: "#14274e",
      muted: "#5a6478",
      headingFont: "palatino",
      bodyFont: "georgia",
      contactIcons: "words",
      social: icon("outline", "accent", 20),
    },
  },
  {
    id: "finance-ledger",
    name: "Ledger",
    group: "Business",
    category: "Finance",
    description: "Two-column contact grid, very structured.",
    layout: "grid",
    design: { accent: "#0b6e4f", text: "#13221c", muted: "#55655d", headingFont: "inter", bodyFont: "inter", social: icon("square", "accent", 20) },
  },
  {
    id: "finance-advisor",
    name: "Advisor",
    group: "Business",
    category: "Finance",
    description: "Calm card with photo and booking-ready layout.",
    layout: "card",
    design: {
      accent: "#2a5d9f",
      surface: "#eef3fa",
      text: "#172338",
      muted: "#5b6880",
      headingFont: "fraunces",
      bodyFont: "helvetica",
      social: icon("circle"),
    },
  },
  {
    id: "health-care",
    name: "Care",
    group: "Business",
    category: "Healthcare",
    description: "Soft teal card that feels trustworthy.",
    layout: "card",
    design: {
      accent: "#0f8b8d",
      surface: "#e9f6f5",
      text: "#12302f",
      muted: "#4f6b6a",
      headingFont: "work-sans",
      bodyFont: "helvetica",
      social: icon("circle"),
    },
  },
  {
    id: "health-clinic",
    name: "Clinic",
    group: "Business",
    category: "Healthcare",
    description: "Clear banner header for practices and clinics.",
    layout: "banner",
    design: { accent: "#2b7de9", text: "#13253f", muted: "#5b6b82", headingFont: "inter", bodyFont: "inter", social: icon("rounded") },
  },
  {
    id: "tech-product",
    name: "Product",
    group: "Business",
    category: "Technology",
    description: "Compact, modern and to the point.",
    layout: "chips",
    design: {
      accent: "#6d4aff",
      surface: "#f1edff",
      text: "#1a1530",
      muted: "#6a6585",
      headingFont: "inter",
      bodyFont: "inter",
      social: icon("rounded", "accent", 20),
    },
    logo: { size: 48 },
  },
  {
    id: "tech-founder",
    name: "Founder",
    group: "Business",
    category: "Technology",
    description: "Photo-forward with grotesk type.",
    layout: "classic",
    design: {
      accent: "#111111",
      text: "#111111",
      muted: "#6b6b6b",
      headingFont: "space-grotesk",
      bodyFont: "helvetica",
      divider: "none",
      social: icon("plain", "mono", 18),
    },
    photo: { shape: "rounded", size: 88 },
  },
  {
    id: "agency-studio",
    name: "Studio",
    group: "Business",
    category: "Creative agency",
    description: "Logo, details and socials in three columns.",
    layout: "split3",
    design: {
      accent: "#ff4d2e",
      text: "#161616",
      muted: "#666666",
      headingFont: "syne",
      bodyFont: "helvetica",
      divider: "accent",
      social: icon("square", "accent", 20),
    },
  },
  {
    id: "hospitality-concierge",
    name: "Concierge",
    group: "Business",
    category: "Hospitality",
    description: "Warm, centred and welcoming.",
    layout: "centered",
    design: {
      accent: "#9a6b3f",
      text: "#2b1f16",
      muted: "#7a6a5c",
      headingFont: "cormorant",
      bodyFont: "georgia",
      nameScale: 1.7,
      social: icon("outline", "accent", 22),
      align: "center",
    },
  },
  {
    id: "hospitality-bistro",
    name: "Bistro",
    group: "Business",
    category: "Hospitality",
    description: "Terracotta card for restaurants and cafés.",
    layout: "card",
    design: {
      accent: "#c0603a",
      surface: "#fbf0ea",
      text: "#2b1d16",
      muted: "#7a6458",
      headingFont: "dm-serif",
      bodyFont: "helvetica",
      social: icon("circle"),
    },
  },
  {
    id: "retail-shop",
    name: "Storefront",
    group: "Business",
    category: "Retail & e-commerce",
    description: "Bright chips and a shop-now button.",
    layout: "chips",
    design: {
      accent: "#e2336b",
      surface: "#fdecf2",
      text: "#2a1520",
      muted: "#7b5d69",
      headingFont: "montserrat",
      bodyFont: "helvetica",
      social: icon("circle", "accent", 20),
    },
  },
  {
    id: "education-faculty",
    name: "Faculty",
    group: "Business",
    category: "Education",
    description: "Academic serif with department line.",
    layout: "stacked",
    design: {
      accent: "#7a1f2b",
      text: "#22161a",
      muted: "#6c5a5e",
      headingFont: "libre-baskerville",
      bodyFont: "georgia",
      social: icon("plain", "accent", 16),
    },
  },
  {
    id: "construction-site",
    name: "Site",
    group: "Business",
    category: "Construction",
    description: "High-contrast yellow and black.",
    layout: "bold",
    design: { accent: "#f2b705", text: "#151515", muted: "#555555", headingFont: "montserrat", bodyFont: "helvetica", social: icon("square", "mono", 20) },
  },
  {
    id: "beauty-salon",
    name: "Salon",
    group: "Business",
    category: "Beauty & wellness",
    description: "Blush tones and an elegant name.",
    layout: "photoRight",
    design: {
      accent: "#c27c88",
      text: "#2d1f22",
      muted: "#8a7378",
      headingFont: "playfair",
      bodyFont: "helvetica",
      divider: "dots",
      social: icon("outline", "accent", 20),
    },
  },
  {
    id: "fitness-coach",
    name: "Coach",
    group: "Business",
    category: "Fitness",
    description: "Energetic, uppercase and bold.",
    layout: "bold",
    design: {
      accent: "#00b37e",
      text: "#0d1b14",
      muted: "#4f6359",
      headingFont: "montserrat",
      bodyFont: "helvetica",
      nameCase: "upper",
      social: icon("circle"),
    },
  },
  {
    id: "nonprofit-cause",
    name: "Cause",
    group: "Business",
    category: "Nonprofit",
    description: "Friendly card with room for a donate button.",
    layout: "card",
    design: {
      accent: "#2f7d32",
      surface: "#eef6ee",
      text: "#1b2b1c",
      muted: "#5b6d5c",
      headingFont: "fraunces",
      bodyFont: "helvetica",
      social: icon("rounded"),
    },
  },
  {
    id: "photo-portfolio",
    name: "Portfolio",
    group: "Business",
    category: "Photography",
    description: "Large photo on the right, minimal text.",
    layout: "photoRight",
    design: {
      accent: "#111111",
      text: "#111111",
      muted: "#777777",
      headingFont: "jost",
      bodyFont: "helvetica",
      divider: "none",
      contactIcons: "none",
      social: icon("plain", "mono", 18),
    },
    photo: { shape: "square", size: 110 },
  },
  {
    id: "music-tour",
    name: "Tour",
    group: "Business",
    category: "Music & events",
    description: "Dark-accent banner for artists and promoters.",
    layout: "banner",
    design: { accent: "#1a1a2e", text: "#1a1a2e", muted: "#5e5e7a", headingFont: "syne", bodyFont: "helvetica", social: icon("circle", "brand") },
  },
  {
    id: "consulting-brief",
    name: "Brief",
    group: "Business",
    category: "Consulting",
    description: "Monogram tile and crisp details.",
    layout: "monogram",
    design: { accent: "#334e68", text: "#102a43", muted: "#627d98", headingFont: "inter", bodyFont: "inter", social: icon("square", "accent", 18) },
  },

  // ── Artistic expression ───────────────────────────────────────────────────
  {
    id: "art-swiss",
    name: "Swiss",
    group: "Artistic",
    category: "Swiss / International",
    description: "Grid, red accent and strict grotesk type.",
    layout: "grid",
    design: {
      accent: "#e30613",
      text: "#000000",
      muted: "#4a4a4a",
      headingFont: "helvetica",
      bodyFont: "helvetica",
      nameScale: 1.8,
      contactIcons: "none",
      divider: "accent",
      social: icon("square", "mono", 18),
    },
  },
  {
    id: "art-bauhaus",
    name: "Bauhaus",
    group: "Artistic",
    category: "Bauhaus",
    description: "Primary-colour monogram and geometric type.",
    layout: "monogram",
    design: {
      accent: "#1d4ed8",
      text: "#111111",
      muted: "#555555",
      headingFont: "jost",
      bodyFont: "jost",
      nameCase: "upper",
      contactIcons: "letters",
      social: icon("square", "brand", 20),
    },
  },
  {
    id: "art-deco",
    name: "Deco",
    group: "Artistic",
    category: "Art Deco",
    description: "Gold on ink, centred, with spaced capitals.",
    layout: "centered",
    design: {
      accent: "#b08d57",
      text: "#14130f",
      muted: "#6f6655",
      headingFont: "cormorant",
      bodyFont: "georgia",
      nameCase: "upper",
      nameScale: 1.6,
      divider: "accent",
      align: "center",
      social: icon("outline", "accent", 20),
    },
  },
  {
    id: "art-brutalist",
    name: "Brutalist",
    group: "Artistic",
    category: "Brutalist",
    description: "Raw mono type, heavy rules, no decoration.",
    layout: "editorial",
    design: {
      accent: "#000000",
      text: "#000000",
      muted: "#333333",
      headingFont: "ibm-plex-mono",
      bodyFont: "courier",
      nameScale: 1.5,
      divider: "accent",
      contactIcons: "words",
      social: icon("square", "mono", 18),
    },
  },
  {
    id: "art-editorial",
    name: "Editorial",
    group: "Artistic",
    category: "Editorial",
    description: "Magazine byline with an oversized serif name.",
    layout: "editorial",
    design: {
      accent: "#9c2c2c",
      text: "#141414",
      muted: "#5c5c5c",
      headingFont: "playfair",
      bodyFont: "georgia",
      nameScale: 1.6,
      divider: "line",
      social: icon("plain", "mono", 16),
    },
  },
  {
    id: "art-gallery",
    name: "Gallery",
    group: "Artistic",
    category: "Gallery",
    description: "Whitespace, small caps and a single photo.",
    layout: "photoRight",
    design: {
      accent: "#1c1c1c",
      text: "#1c1c1c",
      muted: "#8a8a8a",
      headingFont: "cormorant",
      bodyFont: "helvetica",
      nameScale: 1.8,
      divider: "none",
      contactIcons: "none",
      contactInline: true,
      social: icon("plain", "mono", 15),
    },
    photo: { shape: "square", size: 120 },
  },
  {
    id: "art-botanical",
    name: "Botanical",
    group: "Artistic",
    category: "Botanical",
    description: "Sage card, soft serif and leafy calm.",
    layout: "card",
    design: {
      accent: "#6b8f71",
      surface: "#f0f4ee",
      text: "#263029",
      muted: "#6d776f",
      headingFont: "fraunces",
      bodyFont: "georgia",
      divider: "dots",
      social: icon("circle"),
    },
  },
  {
    id: "art-neon",
    name: "Neon",
    group: "Artistic",
    category: "Neon & Y2K",
    description: "Electric violet chips and rounded shapes.",
    layout: "chips",
    design: {
      accent: "#b026ff",
      surface: "#f6e8ff",
      text: "#1a0b2e",
      muted: "#6c5a80",
      headingFont: "syne",
      bodyFont: "helvetica",
      social: icon("rounded", "accent", 22),
    },
  },
  {
    id: "art-retro",
    name: "Retro",
    group: "Artistic",
    category: "Retro",
    description: "Orange sunset banner and warm type.",
    layout: "banner",
    design: { accent: "#e2711d", text: "#3b2314", muted: "#7d5d47", headingFont: "dm-serif", bodyFont: "trebuchet", social: icon("circle") },
  },
  {
    id: "art-minimal-mono",
    name: "Mono",
    group: "Artistic",
    category: "Minimal",
    description: "Black, white and nothing else.",
    layout: "stacked",
    design: {
      accent: "#000000",
      text: "#000000",
      muted: "#6f6f6f",
      headingFont: "inter",
      bodyFont: "inter",
      divider: "none",
      contactIcons: "none",
      social: icon("plain", "mono", 16),
    },
  },
  {
    id: "art-whisper",
    name: "Whisper",
    group: "Artistic",
    category: "Minimal",
    description: "Light, airy and lowercase-friendly.",
    layout: "compact",
    design: {
      accent: "#8c8c8c",
      text: "#2b2b2b",
      muted: "#9a9a9a",
      headingFont: "work-sans",
      bodyFont: "work-sans",
      contactIcons: "none",
      social: icon("plain", "mono", 14),
    },
  },
  {
    id: "art-zine",
    name: "Zine",
    group: "Artistic",
    category: "Zine & collage",
    description: "Bold underline, typewriter details.",
    layout: "bold",
    design: {
      accent: "#ff3366",
      text: "#111111",
      muted: "#555555",
      headingFont: "dm-serif",
      bodyFont: "courier",
      contactIcons: "words",
      social: icon("square", "accent", 18),
    },
  },
  {
    id: "art-script",
    name: "Signature Script",
    group: "Artistic",
    category: "Handwritten",
    description: "Centred with a handwritten sign-off.",
    layout: "centered",
    design: {
      accent: "#3a3a3a",
      text: "#2a2a2a",
      muted: "#7b7b7b",
      headingFont: "cormorant",
      bodyFont: "georgia",
      nameScale: 1.5,
      align: "center",
      divider: "dots",
      social: icon("outline", "mono", 18),
    },
  },
  {
    id: "art-blueprint",
    name: "Blueprint",
    group: "Artistic",
    category: "Architectural",
    description: "Technical mono details on a framed card.",
    layout: "card",
    design: {
      accent: "#1f4e79",
      surface: "#eaf1f8",
      text: "#10263b",
      muted: "#4d6680",
      headingFont: "space-grotesk",
      bodyFont: "ibm-plex-mono",
      contactIcons: "letters",
      social: icon("square", "accent", 18),
    },
  },
  {
    id: "art-noir",
    name: "Noir",
    group: "Artistic",
    category: "Luxury",
    description: "Ink sidebar and refined capitals.",
    layout: "sidebar",
    design: {
      accent: "#14130f",
      text: "#14130f",
      muted: "#6b675d",
      headingFont: "cormorant",
      bodyFont: "helvetica",
      nameCase: "upper",
      nameScale: 1.5,
      social: icon("plain", "mono", 16),
    },
  },
  {
    id: "art-atelier",
    name: "Atelier",
    group: "Artistic",
    category: "Luxury",
    description: "Brass accents and a serif name.",
    layout: "classic",
    design: {
      accent: "#a8834a",
      text: "#16150f",
      muted: "#6b675d",
      headingFont: "cormorant",
      bodyFont: "helvetica",
      nameScale: 1.75,
      divider: "accent",
      social: icon("outline", "accent", 20),
    },
  },
  {
    id: "art-pastel",
    name: "Pastel",
    group: "Artistic",
    category: "Playful",
    description: "Soft mint chips and rounded icons.",
    layout: "chips",
    design: {
      accent: "#2bb3a3",
      surface: "#e5f7f4",
      text: "#173c38",
      muted: "#5d7a76",
      headingFont: "fraunces",
      bodyFont: "helvetica",
      social: icon("rounded", "accent", 20),
    },
  },
  {
    id: "art-poster",
    name: "Poster",
    group: "Artistic",
    category: "Playful",
    description: "A huge name that shouts.",
    layout: "bold",
    design: {
      accent: "#ffcc00",
      text: "#111111",
      muted: "#555555",
      headingFont: "syne",
      bodyFont: "helvetica",
      nameScale: 2,
      nameCase: "upper",
      contactIcons: "none",
      social: icon("circle", "mono"),
    },
  },
  {
    id: "art-ink",
    name: "Ink",
    group: "Artistic",
    category: "Editorial",
    description: "Italic serif byline with compact contacts.",
    layout: "compact",
    design: { accent: "#3b3b98", text: "#1d1d3b", muted: "#6b6b8f", headingFont: "fraunces", bodyFont: "georgia", social: icon("plain", "accent", 16) },
  },
  {
    id: "art-coastal",
    name: "Coastal",
    group: "Artistic",
    category: "Nature",
    description: "Ocean blue sidebar, breezy and light.",
    layout: "sidebar",
    design: { accent: "#1c8a9a", text: "#0f2a33", muted: "#58707a", headingFont: "work-sans", bodyFont: "helvetica", social: icon("circle") },
  },
  {
    id: "art-terracotta",
    name: "Terracotta",
    group: "Artistic",
    category: "Nature",
    description: "Earthy grid with warm accents.",
    layout: "grid",
    design: { accent: "#b5523b", text: "#2b1d16", muted: "#7a6458", headingFont: "dm-serif", bodyFont: "helvetica", social: icon("rounded") },
  },
  {
    id: "art-monolith",
    name: "Monolith",
    group: "Artistic",
    category: "Brutalist",
    description: "Dark monogram tile and stark type.",
    layout: "monogram",
    design: {
      accent: "#111111",
      text: "#111111",
      muted: "#666666",
      headingFont: "space-grotesk",
      bodyFont: "helvetica",
      contactIcons: "letters",
      social: icon("square", "mono", 18),
    },
  },
  {
    id: "art-split",
    name: "Split",
    group: "Artistic",
    category: "Swiss / International",
    description: "Three columns separated by accent rules.",
    layout: "split3",
    design: {
      accent: "#0057ff",
      text: "#0a0a0a",
      muted: "#5a5a5a",
      headingFont: "helvetica",
      bodyFont: "helvetica",
      divider: "accent",
      contactIcons: "none",
      social: icon("square", "accent", 18),
    },
  },
  {
    id: "art-heritage",
    name: "Heritage",
    group: "Artistic",
    category: "Classic",
    description: "Old-world serif, centred and stately.",
    layout: "centered",
    design: {
      accent: "#5c2a2a",
      text: "#2a1414",
      muted: "#7a5c5c",
      headingFont: "libre-baskerville",
      bodyFont: "georgia",
      align: "center",
      contactIcons: "letters",
      social: icon("outline", "accent", 18),
    },
  },
  // ── Added with the builder release ─────────────────────────────────────────
  {
    id: "auto-dealer",
    name: "Showroom",
    group: "Business",
    category: "Automotive",
    description: "Bold name bar and filled contact badges.",
    layout: "bold",
    design: { accent: "#c8102e", text: "#141414", muted: "#5f5f5f", headingFont: "montserrat", bodyFont: "helvetica", social: icon("square", "accent", 20) },
  },
  {
    id: "insurance-trust",
    name: "Assurance",
    group: "Business",
    category: "Insurance",
    description: "Calm card with a soft panel.",
    layout: "card",
    design: {
      accent: "#0b6e69",
      text: "#10302e",
      muted: "#55716e",
      surface: "#eaf5f3",
      headingFont: "work-sans",
      bodyFont: "work-sans",
      social: icon("rounded"),
    },
  },
  {
    id: "marketing-growth",
    name: "Growth",
    group: "Business",
    category: "Marketing",
    description: "Contact chips and a punchy accent.",
    layout: "chips",
    design: {
      accent: "#ff5434",
      text: "#15131a",
      muted: "#6c6873",
      surface: "#fff0ea",
      headingFont: "space-grotesk",
      bodyFont: "inter",
      social: icon("circle", "accent", 20),
    },
  },
  {
    id: "architecture-studio",
    name: "Plan",
    group: "Business",
    category: "Architecture",
    description: "Editorial company line over a fine rule.",
    layout: "editorial",
    design: {
      accent: "#3a3a3a",
      text: "#1a1a1a",
      muted: "#6e6e6e",
      headingFont: "jost",
      bodyFont: "jost",
      divider: "line",
      contactIcons: "letters",
      nameCase: "upper",
      social: icon("plain", "mono", 18),
    },
  },
  {
    id: "dental-smile",
    name: "Bright Smile",
    group: "Business",
    category: "Healthcare",
    description: "Friendly photo-right layout.",
    layout: "photoRight",
    design: { accent: "#1e88e5", text: "#132235", muted: "#5b6b80", headingFont: "montserrat", bodyFont: "helvetica", social: icon("circle", "brand", 20) },
  },
  {
    id: "events-planner",
    name: "Occasion",
    group: "Business",
    category: "Music & events",
    description: "Centred and celebratory.",
    layout: "centered",
    design: {
      accent: "#a4467b",
      text: "#2a1622",
      muted: "#7c5b6d",
      headingFont: "playfair",
      bodyFont: "georgia",
      align: "center",
      contactIcons: "none",
      social: icon("outline", "accent", 20),
    },
  },
  {
    id: "art-midcentury",
    name: "Mid-Century",
    group: "Artistic",
    category: "Retro",
    description: "Mustard, teal and a monogram tile.",
    layout: "monogram",
    design: { accent: "#d39b2a", text: "#203a3a", muted: "#5d7473", headingFont: "dm-serif", bodyFont: "work-sans", social: icon("circle", "accent", 20) },
  },
  {
    id: "art-japandi",
    name: "Japandi",
    group: "Artistic",
    category: "Minimal",
    description: "Quiet stacked layout, warm greys.",
    layout: "stacked",
    design: {
      accent: "#8a7a66",
      text: "#2e2a25",
      muted: "#8b847a",
      headingFont: "cormorant",
      bodyFont: "jost",
      divider: "dots",
      contactIcons: "none",
      social: icon("plain", "mono", 16),
    },
  },
  {
    id: "art-memphis",
    name: "Memphis",
    group: "Artistic",
    category: "Playful",
    description: "Chunky banner in candy colours.",
    layout: "banner",
    design: { accent: "#ff4f9a", text: "#1b1240", muted: "#5a4f80", headingFont: "syne", bodyFont: "space-grotesk", social: icon("square", "accent", 20) },
  },
  {
    id: "art-gradient",
    name: "Aurora",
    group: "Artistic",
    category: "Neon & Y2K",
    description: "Violet sidebar and glowing icons.",
    layout: "sidebar",
    design: { accent: "#7c3aed", text: "#1c1433", muted: "#6c6386", headingFont: "space-grotesk", bodyFont: "inter", social: icon("rounded", "accent", 20) },
  },
  {
    id: "art-typewriter",
    name: "Typewriter",
    group: "Artistic",
    category: "Editorial",
    description: "Monospace details on a compact line.",
    layout: "compact",
    design: {
      accent: "#222222",
      text: "#222222",
      muted: "#666666",
      headingFont: "ibm-plex-mono",
      bodyFont: "ibm-plex-mono",
      contactIcons: "words",
      social: icon("plain", "mono", 16),
    },
  },
  {
    id: "art-gallery-wall",
    name: "Gallery Wall",
    group: "Artistic",
    category: "Gallery",
    description: "Generous grid with a quiet serif.",
    layout: "grid",
    design: {
      accent: "#9c6b3f",
      text: "#1f1a16",
      muted: "#7b7067",
      headingFont: "fraunces",
      bodyFont: "helvetica",
      divider: "line",
      social: icon("outline", "accent", 18),
    },
  },
  ...MODERN_SPECS,
  ...MG_SPECS,
];

function build(spec: Spec): Template {
  return {
    id: spec.id,
    name: spec.name,
    group: spec.group,
    category: spec.category,
    description: spec.description,
    layout: spec.layout,
    design: { ...DEFAULT_DESIGN, ...spec.design, social: { ...DEFAULT_DESIGN.social, ...spec.design?.social } } as Design,
    photo: { shape: spec.photo?.shape ?? "circle", size: spec.photo?.size ?? 84 },
    logo: { size: spec.logo?.size ?? 110 },
    blocks: spec.blocks,
  };
}

export const TEMPLATES: Template[] = SPECS.map(build);
export const TEMPLATE_MAP: Record<string, Template> = Object.fromEntries(TEMPLATES.map((t) => [t.id, t]));
export const DEFAULT_TEMPLATE = "corporate-classic";

export function getTemplate(id: string): Template {
  return TEMPLATE_MAP[id] ?? TEMPLATE_MAP[DEFAULT_TEMPLATE];
}

export const BUSINESS_CATEGORIES = [...new Set(TEMPLATES.filter((t) => t.group === "Business").map((t) => t.category))];
export const MODERN_CATEGORIES = [...new Set(TEMPLATES.filter((t) => t.group === "Modern").map((t) => t.category))];
export const TEMPLATE_GROUPS: TemplateGroup[] = ["Business", "Artistic", "Modern", "Modern Gentlemen"];
export const ARTISTIC_CATEGORIES = [...new Set(TEMPLATES.filter((t) => t.group === "Artistic").map((t) => t.category))];
