/** The approved 90 concepts: stable identities shared by picker, renderer and article presentation. */
export const EDITORIAL_COLLECTION = [
  {
    id: "01",
    number: 1,
    name: "The Edition",
    kind: "section",
    group: "Editorial",
    layout: "edition",
    tone: "theme",
    hero: "portrait",
    chapters: ["The issue", "The cover story", "The weekend", "In conversation"],
    references: "Kinfolk and The Rake",
    description: "Edition: the issue, the cover story, the weekend, in conversation.",
    reference: "/images/editorial-collection/01.webp",
  },
  {
    id: "02",
    number: 2,
    name: "Guest Editor",
    kind: "section",
    group: "People",
    layout: "guest",
    tone: "theme",
    hero: "portrait",
    chapters: ["The object", "The book", "The place", "The idea"],
    references: "Wallpaper guest editor editions",
    description: "Guest Editor: the object, the book, the place, the idea.",
    reference: "/images/editorial-collection/02.webp",
  },
  {
    id: "03",
    number: 3,
    name: "Personal Collections",
    kind: "section",
    group: "Collecting",
    layout: "collection",
    tone: "theme",
    hero: "wide",
    chapters: ["The watch", "The notebook", "The camera", "The book", "The sculpture"],
    references: "Hodinkee collector interviews and Kinfolk essentials",
    description:
      "Personal Collections: the watch, the notebook, the camera, the book, the sculpture.",
    reference: "/images/editorial-collection/03.webp",
  },
  {
    id: "04",
    number: 4,
    name: "On Screen",
    kind: "section",
    group: "Culture",
    layout: "cinema",
    tone: "dark",
    hero: "full",
    chapters: ["The wardrobe", "The watch", "The car"],
    references: "Hodinkee Watching Movies with MG cinema aesthetics",
    description: "On Screen: the wardrobe, the watch, the car.",
    reference: "/images/editorial-collection/04.webp",
  },
  {
    id: "05",
    number: 5,
    name: "MG Originals",
    kind: "section",
    group: "Culture",
    layout: "film",
    tone: "dark",
    hero: "full",
    chapters: ["People", "Places", "Craft"],
    references: "NOWNESS film-series presentation",
    description: "MG Originals: people, places, craft.",
    reference: "/images/editorial-collection/05.webp",
  },
  {
    id: "06",
    number: 6,
    name: "The Event Diary",
    kind: "section",
    group: "Experiences",
    layout: "contact",
    tone: "theme",
    hero: "wide",
    chapters: ["The setting", "The conversation", "The details", "The music"],
    references: "Gentleman's Journal The Diary",
    description: "Event Diary: the setting, the conversation, the details, the music.",
    reference: "/images/editorial-collection/06.webp",
  },
  {
    id: "07",
    number: 7,
    name: "City Guides by MG",
    kind: "section",
    group: "Travel",
    layout: "city",
    tone: "theme",
    hero: "split",
    chapters: ["Stay", "Eat", "Drink", "Discover"],
    references: "Monocle city guides",
    description: "City Guides by MG: stay, eat, drink, discover.",
    reference: "/images/editorial-collection/07.webp",
  },
  {
    id: "08",
    number: 8,
    name: "Five Things Worth Your Time",
    kind: "section",
    group: "Editorial",
    layout: "five",
    tone: "theme",
    hero: "center",
    chapters: ["Watch", "Wear", "Visit", "See", "Listen"],
    references: "Gentleman's Journal Friday Five and Kinfolk curation",
    description: "Five Things Worth Your Time: watch, wear, visit, see, listen.",
    reference: "/images/editorial-collection/08.webp",
  },
  {
    id: "09",
    number: 9,
    name: "The MG List",
    kind: "section",
    group: "People",
    layout: "people",
    tone: "theme",
    hero: "center",
    chapters: ["Film", "Design", "Hospitality", "Style", "Art", "Architecture"],
    references: "Wallpaper creative directories",
    description: "MG List: film, design, hospitality, style, art, architecture.",
    reference: "/images/editorial-collection/09.webp",
  },
  {
    id: "10",
    number: 10,
    name: "The Modern Debate",
    kind: "section",
    group: "Culture",
    layout: "debate",
    tone: "theme",
    hero: "split",
    chapters: ["The case for ease", "The case for occasion"],
    references: "MR PORTER The Style Debate",
    description: "Modern Debate: the case for ease, the case for occasion.",
    reference: "/images/editorial-collection/10.webp",
  },
  {
    id: "11",
    number: 11,
    name: "Ask Modern Gentlemen",
    kind: "section",
    group: "Culture",
    layout: "advice",
    tone: "theme",
    hero: "split",
    chapters: ["What makes a good host?", "What is worth collecting?", "How do you travel well?"],
    references: "Hodinkee expert mailbag",
    description:
      "Ask Modern Gentlemen: what makes a good host?, what is worth collecting?, how do you travel well?.",
    reference: "/images/editorial-collection/11.webp",
  },
  {
    id: "12",
    number: 12,
    name: "Icons Explained",
    kind: "section",
    group: "Collecting",
    layout: "anatomy",
    tone: "theme",
    hero: "split",
    chapters: ["The dial", "The case", "The movement"],
    references: "Hodinkee Reference Points",
    description: "Icons Explained: the dial, the case, the movement.",
    reference: "/images/editorial-collection/12.webp",
  },
  {
    id: "13",
    number: 13,
    name: "At Home With",
    kind: "section",
    group: "Design",
    layout: "home",
    tone: "theme",
    hero: "wide",
    chapters: ["The light", "The objects", "The perspective"],
    references: "The Modern House and NOWNESS In Residence",
    description: "At Home With: the light, the objects, the perspective.",
    reference: "/images/editorial-collection/13.webp",
  },
  {
    id: "14",
    number: 14,
    name: "The Residence Programme",
    kind: "section",
    group: "Experiences",
    layout: "programme",
    tone: "theme",
    hero: "wide",
    chapters: ["In conversation", "The private table", "After dark"],
    references: "Monocle events with MG estate hospitality",
    description: "Residence Programme: in conversation, the private table, after dark.",
    reference: "/images/editorial-collection/14.webp",
  },
  {
    id: "15",
    number: 15,
    name: "The Occasion Edit",
    kind: "section",
    group: "Style",
    layout: "wardrobe",
    tone: "theme",
    hero: "portrait",
    chapters: ["The jacket", "The shoes", "The watch", "The finishing touch"],
    references: "MR PORTER styling and The Rake",
    description: "Occasion Edit: the jacket, the shoes, the watch, the finishing touch.",
    reference: "/images/editorial-collection/15.webp",
  },
  {
    id: "16",
    number: 16,
    name: "Cultural Dossiers",
    kind: "section",
    group: "Culture",
    layout: "dossier",
    tone: "theme",
    hero: "center",
    chapters: ["People", "Places", "Ideas", "After hours"],
    references: "Wallpaper cultural coverage and themed issues",
    description: "Cultural Dossiers: people, places, ideas, after hours.",
    reference: "/images/editorial-collection/16.webp",
  },
  {
    id: "17",
    number: 17,
    name: "From the Archive",
    kind: "section",
    group: "Editorial",
    layout: "archive",
    tone: "theme",
    hero: "center",
    chapters: ["People", "Motoring", "Design"],
    references: "The Road Rat archive and Kinfolk issue library",
    description: "From the Archive: people, motoring, design.",
    reference: "/images/editorial-collection/17.webp",
  },
  {
    id: "18",
    number: 18,
    name: "From the Workshop",
    kind: "section",
    group: "Craft",
    layout: "process",
    tone: "theme",
    hero: "center",
    chapters: ["Draw", "Cut", "Make", "Finish"],
    references: "Kinfolk At Work and craft-focused film series",
    description: "From the Workshop: draw, cut, make, finish.",
    reference: "/images/editorial-collection/18.webp",
  },
  {
    id: "19",
    number: 19,
    name: "Collaborations in Focus",
    kind: "section",
    group: "Experiences",
    layout: "partnership",
    tone: "theme",
    hero: "wide",
    chapters: ["The people", "The materials", "The occasion"],
    references: "Kinfolk partnerships and Monocle partnered guides",
    description: "Collaborations in Focus: the people, the materials, the occasion.",
    reference: "/images/editorial-collection/19.webp",
  },
  {
    id: "20",
    number: 20,
    name: "The Weekend Letter",
    kind: "section",
    group: "Editorial",
    layout: "letter",
    tone: "theme",
    hero: "split",
    chapters: ["The latest letter", "From the archive", "A note from the editor"],
    references: "Monocle Weekend Editions",
    description: "Weekend Letter: the latest letter, from the archive, a note from the editor.",
    reference: "/images/editorial-collection/20.webp",
  },
  {
    id: "21",
    number: 21,
    name: "Cover Story — Portrait",
    kind: "section",
    group: "People",
    layout: "portrait",
    tone: "dark",
    hero: "portrait",
    chapters: ["The cover story", "In conversation", "The next chapter"],
    references: "The Rake portrait covers",
    description: "Cover Story — Portrait: the cover story, in conversation, the next chapter.",
    reference: "/images/editorial-collection/21.webp",
  },
  {
    id: "22",
    number: 22,
    name: "Cover Story — Panorama",
    kind: "section",
    group: "Travel",
    layout: "panorama",
    tone: "theme",
    hero: "full",
    chapters: ["The road", "The destination", "The stay", "The detour"],
    references: "Gentleman's Journal hero hierarchy",
    description: "Cover Story — Panorama: the road, the destination, the stay, the detour.",
    reference: "/images/editorial-collection/22.webp",
  },
  {
    id: "23",
    number: 23,
    name: "The Watch Room",
    kind: "section",
    group: "Collecting",
    layout: "watch",
    tone: "dark",
    hero: "center",
    chapters: ["Everyday", "Occasion", "Collecting"],
    references: "Hodinkee object photography and MG Watch Vault",
    description: "Watch Room: everyday, occasion, collecting.",
    reference: "/images/editorial-collection/23.webp",
  },
  {
    id: "24",
    number: 24,
    name: "48 Hours, Well Spent",
    kind: "section",
    group: "Travel",
    layout: "itinerary",
    tone: "theme",
    hero: "split",
    chapters: ["Friday evening", "Saturday morning", "Saturday evening", "Sunday morning"],
    references: "Monocle guide utility",
    description:
      "48 Hours, Well Spent: friday evening, saturday morning, saturday evening, sunday morning.",
    reference: "/images/editorial-collection/24.webp",
  },
  {
    id: "25",
    number: 25,
    name: "The Private Table",
    kind: "section",
    group: "Experiences",
    layout: "table",
    tone: "dark",
    hero: "full",
    chapters: ["The host", "The menu", "The conversation"],
    references: "Gentleman's Journal event diary and MG hospitality",
    description: "Private Table: the host, the menu, the conversation.",
    reference: "/images/editorial-collection/25.webp",
  },
  {
    id: "26",
    number: 26,
    name: "The Hotel Register",
    kind: "section",
    group: "Travel",
    layout: "hotels",
    tone: "theme",
    hero: "center",
    chapters: ["City", "Coast", "Countryside"],
    references: "Monocle guides and The Modern House architectural photography",
    description: "Hotel Register: city, coast, countryside.",
    reference: "/images/editorial-collection/26.webp",
  },
  {
    id: "27",
    number: 27,
    name: "The Reading Room",
    kind: "section",
    group: "Culture",
    layout: "reading",
    tone: "theme",
    hero: "split",
    chapters: ["On the shelf", "On screen", "From the editor"],
    references: "Kinfolk editorial quiet and collectible print",
    description: "Reading Room: on the shelf, on screen, from the editor.",
    reference: "/images/editorial-collection/27.webp",
  },
  {
    id: "28",
    number: 28,
    name: "Icons in Motion",
    kind: "section",
    group: "Motoring",
    layout: "motion",
    tone: "dark",
    hero: "wide",
    chapters: ["The machines", "The people", "The experience"],
    references: "The Road Rat automotive culture and MG racing-red aesthetic",
    description: "Icons in Motion: the machines, the people, the experience.",
    reference: "/images/editorial-collection/28.webp",
  },
  {
    id: "29",
    number: 29,
    name: "The Photo Essay",
    kind: "section",
    group: "Travel",
    layout: "mosaic",
    tone: "theme",
    hero: "center",
    chapters: ["The landscape", "The details", "The stop", "The stay"],
    references: "Kinfolk spacious photography and Road Rat visual storytelling",
    description: "Photo Essay: the landscape, the details, the stop, the stay.",
    reference: "/images/editorial-collection/29.webp",
  },
  {
    id: "30",
    number: 30,
    name: "The Modern Gentlemen Front Page",
    kind: "section",
    group: "Editorial",
    layout: "frontpage",
    tone: "theme",
    hero: "portrait",
    chapters: [
      "The lead story",
      "The conversation",
      "The weekend edit",
      "MG originals",
      "The residence",
    ],
    references: "A synthesis of Gentleman’s Journal, Kinfolk, Monocle and NOWNESS",
    description:
      "Modern Gentlemen Front Page: the lead story, the conversation, the weekend edit, mg originals, the residence.",
    reference: "/images/editorial-collection/30.webp",
  },
  {
    id: "31",
    number: 31,
    name: "The Sound Room",
    kind: "section",
    group: "Culture",
    layout: "sound",
    tone: "dark",
    hero: "full",
    chapters: ["First record", "Second record", "Third record"],
    references: "NOWNESS cinematic curation and Monocle radio",
    description: "Sound Room: first record, second record, third record.",
    reference: "/images/editorial-collection/31.webp",
  },
  {
    id: "32",
    number: 32,
    name: "The Cellar",
    kind: "section",
    group: "Taste",
    layout: "cellar",
    tone: "theme",
    hero: "split",
    chapters: ["The region", "The maker", "The occasion"],
    references: "The Rake and Gentleman's Journal drinks editorials",
    description: "Cellar: the region, the maker, the occasion.",
    reference: "/images/editorial-collection/32.webp",
  },
  {
    id: "33",
    number: 33,
    name: "The Chef’s Notebook",
    kind: "section",
    group: "Taste",
    layout: "chef",
    tone: "theme",
    hero: "portrait",
    chapters: ["The ingredient", "The technique", "The dish"],
    references: "Kinfolk process storytelling and Monocle hospitality",
    description: "Chef’s Notebook: the ingredient, the technique, the dish.",
    reference: "/images/editorial-collection/33.webp",
  },
  {
    id: "34",
    number: 34,
    name: "The Material Library",
    kind: "section",
    group: "Design",
    layout: "materials",
    tone: "theme",
    hero: "center",
    chapters: ["Stone", "Timber", "Leather", "Linen", "Metal", "Clay"],
    references: "Wallpaper design studies and Kinfolk materiality",
    description: "Material Library: stone, timber, leather, linen, metal, clay.",
    reference: "/images/editorial-collection/34.webp",
  },
  {
    id: "35",
    number: 35,
    name: "Design Dialogues",
    kind: "section",
    group: "People",
    layout: "dialogue",
    tone: "theme",
    hero: "split",
    chapters: ["First perspective", "Second perspective", "The shared idea"],
    references: "Wallpaper creative voices and The Modern House",
    description: "Design Dialogues: first perspective, second perspective, the shared idea.",
    reference: "/images/editorial-collection/35.webp",
  },
  {
    id: "36",
    number: 36,
    name: "The Modern Uniform",
    kind: "section",
    group: "Style",
    layout: "uniform",
    tone: "theme",
    hero: "portrait",
    chapters: ["The coat", "The knit", "The trousers", "The shoes"],
    references: "MR PORTER wearable style and The Rake",
    description: "Modern Uniform: the coat, the knit, the trousers, the shoes.",
    reference: "/images/editorial-collection/36.webp",
  },
  {
    id: "37",
    number: 37,
    name: "A Week of Style",
    kind: "section",
    group: "Style",
    layout: "week",
    tone: "theme",
    hero: "center",
    chapters: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
    references: "MR PORTER practical wardrobe features",
    description: "A Week of Style: monday, tuesday, wednesday, thursday, friday.",
    reference: "/images/editorial-collection/37.webp",
  },
  {
    id: "38",
    number: 38,
    name: "The Season Ahead",
    kind: "section",
    group: "Culture",
    layout: "calendar",
    tone: "theme",
    hero: "wide",
    chapters: ["This month", "Next month", "Looking ahead"],
    references: "Monocle events and Wallpaper cultural coverage",
    description: "Season Ahead: this month, next month, looking ahead.",
    reference: "/images/editorial-collection/38.webp",
  },
  {
    id: "39",
    number: 39,
    name: "The Collector’s Comparison",
    kind: "section",
    group: "Collecting",
    layout: "comparison",
    tone: "theme",
    hero: "center",
    chapters: ["The first object", "The second object"],
    references: "Hodinkee reference guides",
    description: "Collector’s Comparison: the first object, the second object.",
    reference: "/images/editorial-collection/39.webp",
  },
  {
    id: "40",
    number: 40,
    name: "The Grand Tour",
    kind: "section",
    group: "Motoring",
    layout: "tour",
    tone: "theme",
    hero: "full",
    chapters: ["Departure", "The pass", "The detour", "Arrival"],
    references: "The Road Rat automotive travel",
    description: "Grand Tour: departure, the pass, the detour, arrival.",
    reference: "/images/editorial-collection/40.webp",
  },
  {
    id: "41",
    number: 41,
    name: "The Arrival",
    kind: "section",
    group: "Travel",
    layout: "arrival",
    tone: "theme",
    hero: "full",
    chapters: ["Design", "Journey", "Experience"],
    references: "Wallpaper transport design and MG future luxury",
    description: "Arrival: design, journey, experience.",
    reference: "/images/editorial-collection/41.webp",
  },
  {
    id: "42",
    number: 42,
    name: "The Art of Hosting",
    kind: "section",
    group: "Taste",
    layout: "hosting",
    tone: "theme",
    hero: "wide",
    chapters: ["The setting", "The menu", "The atmosphere"],
    references: "Gentleman's Journal gatherings and Kinfolk hospitality",
    description: "Art of Hosting: the setting, the menu, the atmosphere.",
    reference: "/images/editorial-collection/42.webp",
  },
  {
    id: "43",
    number: 43,
    name: "The Private Address",
    kind: "section",
    group: "Experiences",
    layout: "address",
    tone: "dark",
    hero: "portrait",
    chapters: ["The rooms", "The library", "The table"],
    references: "The Modern House architectural storytelling",
    description: "Private Address: the rooms, the library, the table.",
    reference: "/images/editorial-collection/43.webp",
  },
  {
    id: "44",
    number: 44,
    name: "The New Establishment",
    kind: "section",
    group: "People",
    layout: "establishment",
    tone: "theme",
    hero: "center",
    chapters: ["Design", "Culture", "Hospitality", "Craft"],
    references: "Monocle founder profiles and Gentleman's Journal business",
    description: "New Establishment: design, culture, hospitality, craft.",
    reference: "/images/editorial-collection/44.webp",
  },
  {
    id: "45",
    number: 45,
    name: "Object of the Week",
    kind: "section",
    group: "Design",
    layout: "object",
    tone: "theme",
    hero: "split",
    chapters: ["Form", "Material", "Experience"],
    references: "Wallpaper object design and Hodinkee product focus",
    description: "Object of the Week: form, material, experience.",
    reference: "/images/editorial-collection/45.webp",
  },
  {
    id: "46",
    number: 46,
    name: "The Reading List",
    kind: "section",
    group: "Culture",
    layout: "bookshelf",
    tone: "theme",
    hero: "split",
    chapters: [
      "First selection",
      "Second selection",
      "Third selection",
      "Fourth selection",
      "Fifth selection",
    ],
    references: "Kinfolk print culture",
    description:
      "Reading List: first selection, second selection, third selection, fourth selection, fifth selection.",
    reference: "/images/editorial-collection/46.webp",
  },
  {
    id: "47",
    number: 47,
    name: "The Listening Bar",
    kind: "section",
    group: "Culture",
    layout: "listening",
    tone: "dark",
    hero: "full",
    chapters: ["The room", "The sound", "The pour"],
    references: "NOWNESS culture and Monocle city reporting",
    description: "Listening Bar: the room, the sound, the pour.",
    reference: "/images/editorial-collection/47.webp",
  },
  {
    id: "48",
    number: 48,
    name: "The Daily Ritual",
    kind: "section",
    group: "Lifestyle",
    layout: "ritual",
    tone: "theme",
    hero: "center",
    chapters: ["A brighter start", "A refined routine", "A clearer mind"],
    references: "Kinfolk intentional living and MR PORTER grooming",
    description: "Daily Ritual: a brighter start, a refined routine, a clearer mind.",
    reference: "/images/editorial-collection/48.webp",
  },
  {
    id: "49",
    number: 49,
    name: "The Sporting Life",
    kind: "section",
    group: "Lifestyle",
    layout: "sport",
    tone: "theme",
    hero: "portrait",
    chapters: ["The craft", "The perspective", "The style", "The essentials"],
    references: "Gentleman's Journal leisure and The Rake",
    description: "Sporting Life: the craft, the perspective, the style, the essentials.",
    reference: "/images/editorial-collection/49.webp",
  },
  {
    id: "50",
    number: 50,
    name: "The Design Weekend",
    kind: "section",
    group: "Travel",
    layout: "weekend",
    tone: "theme",
    hero: "center",
    chapters: ["Stay", "See", "Discover"],
    references: "Monocle guides and Wallpaper design culture",
    description: "Design Weekend: stay, see, discover.",
    reference: "/images/editorial-collection/50.webp",
  },
  {
    id: "51",
    number: 51,
    name: "The Exhibition",
    kind: "section",
    group: "Culture",
    layout: "exhibition",
    tone: "theme",
    hero: "full",
    chapters: ["The curator", "The programme", "The work"],
    references: "Wallpaper art coverage and gallery minimalism",
    description: "Exhibition: the curator, the programme, the work.",
    reference: "/images/editorial-collection/51.webp",
  },
  {
    id: "52",
    number: 52,
    name: "The Photographer’s Eye",
    kind: "section",
    group: "Culture",
    layout: "portfolio",
    tone: "theme",
    hero: "center",
    chapters: ["Portrait", "Landscape", "Street", "Objects", "Hands", "Architecture"],
    references: "Kinfolk photo essays and NOWNESS creative profiles",
    description: "Photographer’s Eye: portrait, landscape, street, objects, hands, architecture.",
    reference: "/images/editorial-collection/52.webp",
  },
  {
    id: "53",
    number: 53,
    name: "The Next Chapter",
    kind: "section",
    group: "Editorial",
    layout: "next",
    tone: "theme",
    hero: "center",
    chapters: ["Culture", "Travel", "Style"],
    references: "The Rake magazine discovery and MG story navigation",
    description: "Next Chapter: culture, travel, style.",
    reference: "/images/editorial-collection/53.webp",
  },
  {
    id: "54",
    number: 54,
    name: "The Membership Invitation",
    kind: "section",
    group: "Experiences",
    layout: "invitation",
    tone: "dark",
    hero: "portrait",
    chapters: ["Conversations", "Gatherings", "Discovery"],
    references: "Gentleman's Journal Clubhouse and MG community",
    description: "Membership Invitation: conversations, gatherings, discovery.",
    reference: "/images/editorial-collection/54.webp",
  },
  {
    id: "55",
    number: 55,
    name: "The Journey Index",
    kind: "section",
    group: "Travel",
    layout: "destinations",
    tone: "theme",
    hero: "split",
    chapters: ["Europe", "Asia", "North America", "Coastal", "Cities"],
    references: "Monocle destination directories",
    description: "Journey Index: europe, asia, north america, coastal, cities.",
    reference: "/images/editorial-collection/55.webp",
  },
  {
    id: "56",
    number: 56,
    name: "The Atelier Index",
    kind: "section",
    group: "Craft",
    layout: "atelier",
    tone: "theme",
    hero: "portrait",
    chapters: ["Ceramics", "Leather", "Horology"],
    references: "Kinfolk craft profiles and The Rake ateliers",
    description: "Atelier Index: ceramics, leather, horology.",
    reference: "/images/editorial-collection/56.webp",
  },
  {
    id: "57",
    number: 57,
    name: "The Conversation Club",
    kind: "section",
    group: "Culture",
    layout: "conversation",
    tone: "dark",
    hero: "full",
    chapters: ["The latest episode", "The previous conversation", "From the archive"],
    references: "NOWNESS series and Monocle radio",
    description:
      "Conversation Club: the latest episode, the previous conversation, from the archive.",
    reference: "/images/editorial-collection/57.webp",
  },
  {
    id: "58",
    number: 58,
    name: "The Daily Brief",
    kind: "section",
    group: "Editorial",
    layout: "brief",
    tone: "theme",
    hero: "portrait",
    chapters: ["Design", "Culture", "Hospitality", "From the editor", "The object"],
    references: "Monocle newspaper hierarchy",
    description: "Daily Brief: design, culture, hospitality, from the editor, the object.",
    reference: "/images/editorial-collection/58.webp",
  },
  {
    id: "59",
    number: 59,
    name: "The Hotel Notebook",
    kind: "section",
    group: "Travel",
    layout: "notebook",
    tone: "theme",
    hero: "split",
    chapters: ["Arrivals", "Rooms", "Food and drink", "Design details", "People", "The feeling"],
    references: "The Modern House interiors and Kinfolk personal travel",
    description:
      "Hotel Notebook: arrivals, rooms, food and drink, design details, people, the feeling.",
    reference: "/images/editorial-collection/59.webp",
  },
  {
    id: "60",
    number: 60,
    name: "The Experience Index",
    kind: "section",
    group: "Experiences",
    layout: "experiences",
    tone: "theme",
    hero: "wide",
    chapters: ["The residence", "Icons in motion", "In conversation"],
    references: "Monocle events and MG cultural platforms",
    description: "Experience Index: the residence, icons in motion, in conversation.",
    reference: "/images/editorial-collection/60.webp",
  },
  {
    id: "61",
    number: 61,
    name: "The Magazine Long Read",
    kind: "article",
    group: "Editorial",
    layout: "essay",
    tone: "theme",
    hero: "center",
    chapters: ["A calmer mind", "Better choices", "Richer connections", "A meaningful tomorrow"],
    references: "Kinfolk spacious reading and The Rake",
    description:
      "Magazine Long Read: a calmer mind, better choices, richer connections, a meaningful tomorrow.",
    reference: "/images/editorial-collection/61.webp",
  },
  {
    id: "62",
    number: 62,
    name: "The Cover Interview",
    kind: "article",
    group: "People",
    layout: "qa",
    tone: "theme",
    hero: "split",
    chapters: ["The starting point", "The turning point", "What comes next"],
    references: "The Rake portraiture and Kinfolk conversations",
    description: "Cover Interview: the starting point, the turning point, what comes next.",
    reference: "/images/editorial-collection/62.webp",
  },
  {
    id: "63",
    number: 63,
    name: "The Collector Profile",
    kind: "article",
    group: "Collecting",
    layout: "objects",
    tone: "theme",
    hero: "wide",
    chapters: ["The first object", "The second object", "The third object"],
    references: "Hodinkee personal collections",
    description: "Collector Profile: the first object, the second object, the third object.",
    reference: "/images/editorial-collection/63.webp",
  },
  {
    id: "64",
    number: 64,
    name: "The Film Feature",
    kind: "article",
    group: "Culture",
    layout: "film",
    tone: "theme",
    hero: "full",
    chapters: ["The film", "Behind the scenes", "The director"],
    references: "NOWNESS and cinematic editorial",
    description: "Film Feature: the film, behind the scenes, the director.",
    reference: "/images/editorial-collection/64.webp",
  },
  {
    id: "65",
    number: 65,
    name: "The Watch Review",
    kind: "article",
    group: "Collecting",
    layout: "review",
    tone: "theme",
    hero: "full",
    chapters: ["On the wrist", "The dial", "The case", "The movement"],
    references: "Hodinkee product expertise",
    description: "Watch Review: on the wrist, the dial, the case, the movement.",
    reference: "/images/editorial-collection/65.webp",
  },
  {
    id: "66",
    number: 66,
    name: "The Road Test",
    kind: "article",
    group: "Motoring",
    layout: "road",
    tone: "theme",
    hero: "full",
    chapters: ["First impressions", "On the road", "The details", "The verdict"],
    references: "The Road Rat",
    description: "Road Test: first impressions, on the road, the details, the verdict.",
    reference: "/images/editorial-collection/66.webp",
  },
  {
    id: "67",
    number: 67,
    name: "The City Field Guide",
    kind: "article",
    group: "Travel",
    layout: "guide",
    tone: "theme",
    hero: "full",
    chapters: ["Stay", "Eat", "Drink", "Discover"],
    references: "Monocle travel guides",
    description: "City Field Guide: stay, eat, drink, discover.",
    reference: "/images/editorial-collection/67.webp",
  },
  {
    id: "68",
    number: 68,
    name: "The Hotel Review",
    kind: "article",
    group: "Travel",
    layout: "review",
    tone: "theme",
    hero: "center",
    chapters: ["Arrival", "The rooms", "The table", "The feeling"],
    references: "Monocle hospitality and The Modern House",
    description: "Hotel Review: arrival, the rooms, the table, the feeling.",
    reference: "/images/editorial-collection/68.webp",
  },
  {
    id: "69",
    number: 69,
    name: "The Home Tour",
    kind: "article",
    group: "Design",
    layout: "rooms",
    tone: "theme",
    hero: "wide",
    chapters: ["The living room", "The study", "The courtyard"],
    references: "The Modern House and NOWNESS In Residence",
    description: "Home Tour: the living room, the study, the courtyard.",
    reference: "/images/editorial-collection/69.webp",
  },
  {
    id: "70",
    number: 70,
    name: "The Maker Profile",
    kind: "article",
    group: "Craft",
    layout: "process",
    tone: "theme",
    hero: "reverse",
    chapters: ["The maker", "Shaping", "Tools", "The result"],
    references: "Kinfolk At Work",
    description: "Maker Profile: the maker, shaping, tools, the result.",
    reference: "/images/editorial-collection/70.webp",
  },
  {
    id: "71",
    number: 71,
    name: "The Style Essay",
    kind: "article",
    group: "Style",
    layout: "essay",
    tone: "theme",
    hero: "split",
    chapters: ["The intention", "The details", "Living with it"],
    references: "MR PORTER essays and The Rake",
    description: "Style Essay: the intention, the details, living with it.",
    reference: "/images/editorial-collection/71.webp",
  },
  {
    id: "72",
    number: 72,
    name: "The Occasion Guide",
    kind: "article",
    group: "Style",
    layout: "guide",
    tone: "theme",
    hero: "full",
    chapters: ["The jacket", "The details", "The finish"],
    references: "MR PORTER practical style",
    description: "Occasion Guide: the jacket, the details, the finish.",
    reference: "/images/editorial-collection/72.webp",
  },
  {
    id: "73",
    number: 73,
    name: "The Photographic Essay",
    kind: "article",
    group: "Travel",
    layout: "gallery",
    tone: "theme",
    hero: "full",
    chapters: ["A higher view", "Morning light", "The road", "A quieter hour"],
    references: "Kinfolk art-book restraint",
    description: "Photographic Essay: a higher view, morning light, the road, a quieter hour.",
    reference: "/images/editorial-collection/73.webp",
  },
  {
    id: "74",
    number: 74,
    name: "The Two-Voice Debate",
    kind: "article",
    group: "Culture",
    layout: "debate",
    tone: "theme",
    hero: "diptych",
    chapters: ["The case for restraint", "The case for abundance", "The editor’s note"],
    references: "MR PORTER The Style Debate",
    description:
      "Two-Voice Debate: the case for restraint, the case for abundance, the editor’s note.",
    reference: "/images/editorial-collection/74.webp",
  },
  {
    id: "75",
    number: 75,
    name: "The Editor’s Letter",
    kind: "article",
    group: "Editorial",
    layout: "letter",
    tone: "theme",
    hero: "letter",
    chapters: ["A note from the editor"],
    references: "Kinfolk and Monocle letters",
    description: "Editor’s Letter: a note from the editor.",
    reference: "/images/editorial-collection/75.webp",
  },
  {
    id: "76",
    number: 76,
    name: "The Cultural Dispatch",
    kind: "article",
    group: "Culture",
    layout: "dispatch",
    tone: "theme",
    hero: "center",
    chapters: ["A city of layers", "A culture of ritual", "Looking ahead"],
    references: "Monocle field reporting",
    description: "Cultural Dispatch: a city of layers, a culture of ritual, looking ahead.",
    reference: "/images/editorial-collection/76.webp",
  },
  {
    id: "77",
    number: 77,
    name: "The Exhibition Review",
    kind: "article",
    group: "Culture",
    layout: "exhibition",
    tone: "theme",
    hero: "wide",
    chapters: ["The first encounter", "The central idea", "The work in context"],
    references: "Wallpaper art criticism",
    description: "Exhibition Review: the first encounter, the central idea, the work in context.",
    reference: "/images/editorial-collection/77.webp",
  },
  {
    id: "78",
    number: 78,
    name: "The Book Review",
    kind: "article",
    group: "Culture",
    layout: "book",
    tone: "theme",
    hero: "reverse",
    chapters: ["The premise", "The reading", "The verdict"],
    references: "Kinfolk books and cultural essays",
    description: "Book Review: the premise, the reading, the verdict.",
    reference: "/images/editorial-collection/78.webp",
  },
  {
    id: "79",
    number: 79,
    name: "The Listening Notes",
    kind: "article",
    group: "Culture",
    layout: "playlist",
    tone: "theme",
    hero: "full",
    chapters: ["The opening track", "A change of pace", "Late night listening", "The final record"],
    references: "NOWNESS music and Monocle audio",
    description:
      "Listening Notes: the opening track, a change of pace, late night listening, the final record.",
    reference: "/images/editorial-collection/79.webp",
  },
  {
    id: "80",
    number: 80,
    name: "The Chef Conversation",
    kind: "article",
    group: "Taste",
    layout: "qa",
    tone: "theme",
    hero: "wide",
    chapters: [
      "What does a good table mean to you?",
      "Where do you find inspiration?",
      "What do you want guests to take away?",
    ],
    references: "Kinfolk hospitality profiles",
    description:
      "Chef Conversation: what does a good table mean to you?, where do you find inspiration?, what do you want guests to take away?.",
    reference: "/images/editorial-collection/80.webp",
  },
  {
    id: "81",
    number: 81,
    name: "The Hosting Guide",
    kind: "article",
    group: "Taste",
    layout: "steps",
    tone: "theme",
    hero: "full",
    chapters: [
      "Set the scene",
      "Consider the menu",
      "Attend to the details",
      "Create a rhythm",
      "End on a lasting note",
    ],
    references: "Gentleman's Journal hospitality",
    description:
      "Hosting Guide: set the scene, consider the menu, attend to the details, create a rhythm, end on a lasting note.",
    reference: "/images/editorial-collection/81.webp",
  },
  {
    id: "82",
    number: 82,
    name: "The Event Report",
    kind: "article",
    group: "Experiences",
    layout: "report",
    tone: "theme",
    hero: "full",
    chapters: ["The setting", "The conversation", "The details", "The closing moments"],
    references: "Gentleman's Journal The Diary",
    description: "Event Report: the setting, the conversation, the details, the closing moments.",
    reference: "/images/editorial-collection/82.webp",
  },
  {
    id: "83",
    number: 83,
    name: "The Residence Journal",
    kind: "article",
    group: "Experiences",
    layout: "residence",
    tone: "theme",
    hero: "wide",
    chapters: ["A place to gather", "In conversation", "A room-by-room journey"],
    references: "MG hospitality and NOWNESS architecture",
    description: "Residence Journal: a place to gather, in conversation, a room-by-room journey.",
    reference: "/images/editorial-collection/83.webp",
  },
  {
    id: "84",
    number: 84,
    name: "The Collaboration Story",
    kind: "article",
    group: "Experiences",
    layout: "collaboration",
    tone: "theme",
    hero: "wide",
    chapters: ["The creative intent", "The materials", "The process", "The result"],
    references: "Kinfolk partnerships and Wallpaper bespoke features",
    description:
      "Collaboration Story: the creative intent, the materials, the process, the result.",
    reference: "/images/editorial-collection/84.webp",
  },
  {
    id: "85",
    number: 85,
    name: "The Object History",
    kind: "article",
    group: "Collecting",
    layout: "chronology",
    tone: "theme",
    hero: "split",
    chapters: ["Origins", "Development", "A cultural moment", "Today"],
    references: "Hodinkee Reference Points and The Road Rat history",
    description: "Object History: origins, development, a cultural moment, today.",
    reference: "/images/editorial-collection/85.webp",
  },
  {
    id: "86",
    number: 86,
    name: "The Reference Guide",
    kind: "article",
    group: "Collecting",
    layout: "reference",
    tone: "theme",
    hero: "full",
    chapters: [
      "A brief history",
      "How it works",
      "Key components",
      "How to choose",
      "Care and ownership",
      "Glossary",
    ],
    references: "Hodinkee comprehensive explainers",
    description:
      "Reference Guide: a brief history, how it works, key components, how to choose, care and ownership, glossary.",
    reference: "/images/editorial-collection/86.webp",
  },
  {
    id: "87",
    number: 87,
    name: "The Weekend Itinerary",
    kind: "article",
    group: "Travel",
    layout: "itinerary",
    tone: "theme",
    hero: "wide",
    chapters: ["Friday", "Saturday", "Sunday"],
    references: "Monocle practical travel",
    description: "Weekend Itinerary: friday, saturday, sunday.",
    reference: "/images/editorial-collection/87.webp",
  },
  {
    id: "88",
    number: 88,
    name: "The Personal Essentials",
    kind: "article",
    group: "Lifestyle",
    layout: "essentials",
    tone: "theme",
    hero: "wide",
    chapters: [
      "The book",
      "The camera",
      "The jacket",
      "The record",
      "The place",
      "The table",
      "The notebook",
      "The city",
      "The ritual",
      "The people",
    ],
    references: "Kinfolk Starter For Ten",
    description:
      "Personal Essentials: the book, the camera, the jacket, the record, the place, the table, the notebook, the city, the ritual, the people.",
    reference: "/images/editorial-collection/88.webp",
  },
  {
    id: "89",
    number: 89,
    name: "The Architecture Study",
    kind: "article",
    group: "Design",
    layout: "architecture",
    tone: "theme",
    hero: "full",
    chapters: ["The site", "The light", "The materials", "The plan"],
    references: "The Modern House and Wallpaper",
    description: "Architecture Study: the site, the light, the materials, the plan.",
    reference: "/images/editorial-collection/89.webp",
  },
  {
    id: "90",
    number: 90,
    name: "The Grand Narrative",
    kind: "article",
    group: "Editorial",
    layout: "narrative",
    tone: "theme",
    hero: "full",
    chapters: ["A different rhythm", "Places in between", "A wider perspective", "The road ahead"],
    references: "The Road Rat long-form and Kinfolk magazine editions",
    description:
      "Grand Narrative: a different rhythm, places in between, a wider perspective, the road ahead.",
    reference: "/images/editorial-collection/90.webp",
  },
] as const;
export type EditorialConcept = (typeof EDITORIAL_COLLECTION)[number];
export type EditorialConceptId = EditorialConcept["id"];
export type EditorialCollectionType = `mgCollection${EditorialConceptId}`;
export const editorialConcept = (id: string) => EDITORIAL_COLLECTION.find((c) => c.id === id);
export const collectionType = (id: EditorialConceptId): EditorialCollectionType =>
  `mgCollection${id}`;
export const collectionFromType = (type: string) =>
  EDITORIAL_COLLECTION.find((c) => collectionType(c.id) === type);
export const collectionArticlePresets = EDITORIAL_COLLECTION.filter(
  (c) => c.kind === "article"
).map((c) => ({
  id: `collection-${c.id}` as const,
  name: `${c.id} · ${c.name}`,
  layout: `c${c.id}` as const,
  group: "MG 90 collection",
  description: c.description,
  concept: c.id,
  hero: c.hero,
}));
