export const HERO_STUDIO_PRESETS = [
  { value: "editorialSplit", module: "01", label: "Editorial Split Hero", layout: "split" },
  { value: "fullBleedCover", module: "69", label: "Full-Bleed Cover", layout: "cover" },
  { value: "typeMasthead", module: "70", label: "Type Masthead", layout: "masthead" },
  { value: "triptych", module: "71", label: "Triptych", layout: "triptych" },
  { value: "broadsheetStack", module: "72", label: "Broadsheet Stack", layout: "broadsheet" },
  { value: "sidebarRail", module: "73", label: "Sidebar Rail", layout: "rail" },
  { value: "redField", module: "74", label: "Red Field", layout: "field" },
  { value: "splitDiagonal", module: "75", label: "Split Diagonal", layout: "diagonal" },
  { value: "framedCover", module: "76", label: "Framed Cover", layout: "framed" },
  { value: "quoteOpener", module: "77", label: "Quote Opener", layout: "quote" },
  { value: "collageGrid", module: "78", label: "Collage Grid", layout: "collage" },
  { value: "filmStill", module: "79", label: "Film Still", layout: "cinema" },
  { value: "countdownDrop", module: "80", label: "Countdown Drop", layout: "countdown" },
  { value: "indexOpener", module: "81", label: "Index Opener", layout: "index" },
  { value: "marqueeTicker", module: "82", label: "Marquee Ticker", layout: "ticker" },
  { value: "ledgerSplit", module: "83", label: "Ledger Split", layout: "ledger" },
  { value: "coverStar", module: "84", label: "Cover Star", layout: "portrait" },
  { value: "classicMasthead", module: "85", label: "Classic Masthead", layout: "masthead" },
  { value: "salonSplit", module: "86", label: "Salon Split", layout: "split" },
  { value: "heatBoard", module: "87", label: "Heat Board", layout: "board" },
  { value: "centerfold", module: "88", label: "Centerfold", layout: "centerfold" },
  { value: "dropFeed", module: "89", label: "Drop Feed", layout: "feed" },
  { value: "interiorView", module: "90", label: "Interior View", layout: "framed" },
  { value: "thePicks", module: "91", label: "The Picks", layout: "cards" },
  { value: "screeningRoom", module: "92", label: "Screening Room", layout: "cinema" },
  { value: "theDaily", module: "93", label: "The Daily", layout: "broadsheet" },
  { value: "theEssay", module: "94", label: "The Essay", layout: "quote" },
  { value: "theHundred", module: "95", label: "The Hundred", layout: "index" },
  { value: "profileDuplex", module: "96", label: "Profile Duplex", layout: "duplex" },
  { value: "membersHour", module: "97", label: "Members' Hour", layout: "ledger" },
  { value: "doublePortrait", module: "98", label: "Double Portrait", layout: "duplex" },
  { value: "quietLuxury", module: "99", label: "Quiet Luxury", layout: "minimal" },
  { value: "versus", module: "100", label: "Versus", layout: "versus" },
  { value: "theRanking", module: "101", label: "The Ranking", layout: "board" },
  { value: "dropClock", module: "102", label: "Drop Clock", layout: "countdown" },
  { value: "afterDark", module: "103", label: "After Dark", layout: "cover" },
  { value: "theIssue", module: "104", label: "The Issue", layout: "centerfold" },
  { value: "coverWall", module: "105", label: "Cover Wall", layout: "wall" },
  { value: "indexMono", module: "106", label: "Index Mono", layout: "index" },
  { value: "lowerCase", module: "107", label: "Lower Case", layout: "minimal" },
  { value: "theWire", module: "108", label: "The Wire", layout: "ticker" },
  { value: "openDoor", module: "109", label: "Open Door", layout: "split" },
  { value: "filmstrip", module: "110", label: "Filmstrip", layout: "filmstrip" },
  { value: "roomIndex", module: "111", label: "Room Index", layout: "rail" },
  { value: "theSeal", module: "112", label: "The Seal", layout: "seal" },
  { value: "newFiction", module: "113", label: "New Fiction", layout: "quote" },
  { value: "liveDesk", module: "114", label: "Live Desk", layout: "live" },
  { value: "stillLife", module: "115", label: "Still Life", layout: "portrait" },
  { value: "vogueCoverStory", module: "116", label: "Vogue 6A · Cover Story", layout: "portrait" },
  {
    value: "vogueCenteredMasthead",
    module: "117",
    label: "Vogue 6B · Centered Masthead",
    layout: "masthead",
  },
  { value: "vogueAsymmetric", module: "118", label: "Vogue 6C · Asymmetric", layout: "collage" },
  {
    value: "voguePortraitGrid",
    module: "119",
    label: "Vogue 6D · Portrait Grid",
    layout: "duplex",
  },
  {
    value: "vogueRunwayStrip",
    module: "120",
    label: "Vogue 6E · Runway Strip",
    layout: "filmstrip",
  },
  { value: "voguePullQuote", module: "121", label: "Vogue 6F · Pull-Quote", layout: "quote" },
  { value: "vogueSplitHero", module: "122", label: "Vogue 6G · Split Hero", layout: "split" },
  {
    value: "vogueStackedFeatures",
    module: "123",
    label: "Vogue 6H · Stacked Features",
    layout: "feed",
  },
  { value: "vogueIndex", module: "124", label: "Vogue 6I · The Index", layout: "index" },
  { value: "voguePhotoMosaic", module: "125", label: "Vogue 6J · Photo Mosaic", layout: "wall" },
] as const;

export type HeroStudioPreset = (typeof HERO_STUDIO_PRESETS)[number];
export type HeroStudioVariant = HeroStudioPreset["value"];
export type HeroStudioLayout = HeroStudioPreset["layout"];

export const HERO_STUDIO_VARIANTS = HERO_STUDIO_PRESETS.map((preset) => preset.value);

export function heroStudioPreset(value: HeroStudioVariant): HeroStudioPreset {
  return HERO_STUDIO_PRESETS.find((preset) => preset.value === value) ?? HERO_STUDIO_PRESETS[0];
}
