export const SECTION_STUDIO_PRESETS = [
  ["categoryRail", "02", "Category Rail", "cards"],
  ["theIndex", "03", "The Index", "list"],
  ["longReadFeature", "04", "Long-Read Feature", "feature"],
  ["theStore", "05", "The Store", "commerce"],
  ["contributorSpotlight", "06", "Contributor Spotlight", "profile"],
  ["manifestoPullQuote", "07", "Manifesto Pull-Quote", "quote"],
  ["byTheNumbers", "08", "By the Numbers", "stats"],
  ["theArchive", "09", "The Archive", "grid"],
  ["socialGallery", "10", "Social Gallery", "gallery"],
  ["theDebate", "11", "The Debate", "interview"],
  ["theFieldGuide", "12", "The Field Guide", "list"],
  ["specComparison", "13", "Spec Comparison", "comparison"],
  ["dispatchBanner", "14", "Dispatch Banner", "banner"],
  ["theInterview", "15", "The Interview", "interview"],
  ["briefHistory", "16", "A Brief History", "timeline"],
  ["letterFromEditor", "17", "Letter from the Editor", "letter"],
  ["memberVoices", "18", "Member Voices", "quotes"],
  ["theBriefing", "19", "The Briefing", "list"],
  ["featuredSeries", "20", "Featured Series", "cards"],
  ["startHere", "21", "Start Here", "steps"],
  ["currentIssue", "22", "Current Issue", "issue"],
  ["membershipTiers", "23", "Membership Tiers", "pricing"],
  ["theCalendar", "24", "The Calendar", "calendar"],
  ["destinations", "25", "Destinations", "gallery"],
  ["editorsDesk", "26", "Editors' Desk", "profile"],
  ["coverTakeover", "27", "Cover Takeover", "feature"],
  ["theDrop", "28", "The Drop", "commerce"],
  ["profileLead", "29", "Profile Lead", "profile"],
  ["fitCheck", "30", "Fit Check", "lookbook"],
  ["videoHub", "31", "Video Hub", "video"],
  ["theList", "32", "The List", "list"],
  ["theAwards", "33", "The Awards", "awards"],
  ["theRegimen", "34", "The Regimen", "steps"],
  ["watchOfWeek", "35", "Watch of the Week", "feature"],
  ["whatIveLearned", "36", "What I've Learned", "quote"],
  ["theOpEds", "37", "The Op-Eds", "cards"],
  ["bigReadOpener", "38", "The Big Read Opener", "feature"],
  ["weekendWatchlist", "39", "Weekend Watchlist", "cards"],
  ["askMg", "40", "Ask MG", "advice"],
  ["bestBars", "41", "Best Bars", "directory"],
  ["heritageBand", "42", "Heritage Band", "banner"],
  ["inPartnership", "43", "In Partnership", "feature"],
  ["theRundown", "44", "The Rundown", "list"],
  ["motoringSpotlight", "45", "Motoring Spotlight", "feature"],
  ["interiorsFeature", "46", "Interiors Feature", "feature"],
  ["theObjects", "47", "The Objects", "commerce"],
  ["theLounge", "48", "The Lounge", "cards"],
  ["theCloth", "49", "The Cloth", "feature"],
  ["theCabinet", "50", "The Cabinet", "commerce"],
  ["heatCheck", "51", "Heat Check", "awards"],
  ["trendingNow", "52", "Trending Now", "list"],
  ["cultureMosaic", "53", "Culture Mosaic", "mosaic"],
  ["theVote", "54", "The Vote", "poll"],
  ["overheard", "55", "Overheard", "quotes"],
  ["onRotation", "56", "On Rotation", "audio"],
  ["theUniform", "57", "The Uniform", "lookbook"],
  ["pricePoints", "58", "Price Points", "comparison"],
  ["theRestoration", "59", "The Restoration", "beforeAfter"],
  ["seasonalEdit", "60", "The Seasonal Edit", "commerce"],
  ["readersGarage", "61", "Reader's Garage", "gallery"],
  ["theGlossary", "62", "The Glossary", "glossary"],
  ["debriefAloud", "63", "The Debrief, Aloud", "audio"],
  ["theMarketplace", "64", "The Marketplace", "commerce"],
  ["anatomyOf", "65", "Anatomy Of", "anatomy"],
  ["secondOpinion", "66", "Second Opinion", "interview"],
  ["theWager", "67", "The Wager", "scorecard"],
  ["houseRules", "68", "House Rules", "steps"],
  ["categoryPillBar", "126", "Category Pill Bar", "pills"],
  ["heroPostGrid", "127", "Hero Post Grid (1 + 3)", "leadGrid"],
  ["latestFilmCarousel", "128", "Latest Film Carousel", "carousel"],
  ["featuredPostBand", "129", "Featured Post Band", "banner"],
  ["latestNewsThreeUp", "130", "Latest News Three-Up", "cards"],
  ["filterableArchive", "131", "Filterable Archive Grid", "archive"],
  ["subscribeCtaSplit", "132", "Subscribe CTA Split", "subscribe"],
  ["socialFollowStrip", "133", "Social Follow Strip", "social"],
  ["megaFooter", "134", "Mega Footer", "footer"],
  ["newsletterModal", "135", "Newsletter Modal", "modal"],
  ["contributorsRow", "136", "Contributors Row", "profile"],
  ["trendingTicker", "137", "Trending Ticker", "ticker"],
  ["listSidebar", "138", "List + Sidebar", "sidebar"],
  ["searchResults", "139", "Search Overlay Results", "search"],
  ["paginationLoadMore", "140", "Pagination / Load More", "pagination"],
  ["announcementBar", "141", "Announcement Bar", "announcement"],
  ["audioPodcastList", "142", "Audio / Podcast List", "audio"],
  ["topicCloud", "143", "Topic Cloud", "topics"],
  ["editorsLetter", "144", "Editor's Letter", "letter"],
  ["relatedReading", "145", "Related Reading Strip", "cards"],
] as const;

export type SectionStudioPreset = (typeof SECTION_STUDIO_PRESETS)[number];
export type SectionStudioVariant = SectionStudioPreset[0];
export type SectionStudioLayout = SectionStudioPreset[3];

export function sectionStudioPreset(value: SectionStudioVariant): SectionStudioPreset {
  return SECTION_STUDIO_PRESETS.find((preset) => preset[0] === value) ?? SECTION_STUDIO_PRESETS[0];
}
