export const SECTION_STUDIO_PRESETS = [
  ["categoryRail", "002", "Category Rail", "cards"],
  ["theIndex", "003", "The Index", "list"],
  ["longReadFeature", "004", "Long-Read Feature", "feature"],
  ["theStore", "005", "The Store", "commerce"],
  ["contributorSpotlight", "006", "Contributor Spotlight", "profile"],
  ["manifestoPullQuote", "007", "Manifesto Pull-Quote", "quote"],
  ["byTheNumbers", "008", "By the Numbers", "stats"],
  ["theArchive", "009", "The Archive", "grid"],
  ["socialGallery", "010", "Social Gallery", "gallery"],
  ["theDebate", "011", "The Debate", "interview"],
  ["theFieldGuide", "012", "The Field Guide", "list"],
  ["specComparison", "013", "Spec Comparison", "comparison"],
  ["dispatchBanner", "014", "Dispatch Banner", "banner"],
  ["theInterview", "015", "The Interview", "interview"],
  ["briefHistory", "016", "A Brief History", "timeline"],
  ["letterFromEditor", "017", "Letter from the Editor", "letter"],
  ["memberVoices", "018", "Member Voices", "quotes"],
  ["theBriefing", "019", "The Briefing", "list"],
  ["featuredSeries", "020", "Featured Series", "cards"],
  ["startHere", "021", "Start Here", "steps"],
  ["currentIssue", "022", "Current Issue", "issue"],
  ["membershipTiers", "023", "Membership Tiers", "pricing"],
  ["theCalendar", "024", "The Calendar", "calendar"],
  ["destinations", "025", "Destinations", "gallery"],
  ["editorsDesk", "026", "Editors' Desk", "profile"],
  ["coverTakeover", "027", "Cover Takeover", "feature"],
  ["theDrop", "028", "The Drop", "commerce"],
  ["profileLead", "029", "Profile Lead", "profile"],
  ["fitCheck", "030", "Fit Check", "lookbook"],
  ["videoHub", "031", "Video Hub", "video"],
  ["theList", "032", "The List", "list"],
  ["theAwards", "033", "The Awards", "awards"],
  ["theRegimen", "034", "The Regimen", "steps"],
  ["watchOfWeek", "035", "Watch of the Week", "feature"],
  ["whatIveLearned", "036", "What I've Learned", "quote"],
  ["theOpEds", "037", "The Op-Eds", "cards"],
  ["bigReadOpener", "038", "The Big Read Opener", "feature"],
  ["weekendWatchlist", "039", "Weekend Watchlist", "cards"],
  ["askMg", "040", "Ask MG", "advice"],
  ["bestBars", "041", "Best Bars", "directory"],
  ["heritageBand", "042", "Heritage Band", "banner"],
  ["inPartnership", "043", "In Partnership", "feature"],
  ["theRundown", "044", "The Rundown", "list"],
  ["motoringSpotlight", "045", "Motoring Spotlight", "feature"],
  ["interiorsFeature", "046", "Interiors Feature", "feature"],
  ["theObjects", "047", "The Objects", "commerce"],
  ["theLounge", "048", "The Lounge", "cards"],
  ["theCloth", "049", "The Cloth", "feature"],
  ["theCabinet", "050", "The Cabinet", "commerce"],
  ["heatCheck", "051", "Heat Check", "awards"],
  ["trendingNow", "052", "Trending Now", "list"],
  ["cultureMosaic", "053", "Culture Mosaic", "mosaic"],
  ["theVote", "054", "The Vote", "poll"],
  ["overheard", "055", "Overheard", "quotes"],
  ["onRotation", "056", "On Rotation", "audio"],
  ["theUniform", "057", "The Uniform", "lookbook"],
  ["pricePoints", "058", "Price Points", "comparison"],
  ["theRestoration", "059", "The Restoration", "beforeAfter"],
  ["seasonalEdit", "060", "The Seasonal Edit", "commerce"],
  ["readersGarage", "061", "Reader's Garage", "gallery"],
  ["theGlossary", "062", "The Glossary", "glossary"],
  ["debriefAloud", "063", "The Debrief, Aloud", "audio"],
  ["theMarketplace", "064", "The Marketplace", "commerce"],
  ["anatomyOf", "065", "Anatomy Of", "anatomy"],
  ["secondOpinion", "066", "Second Opinion", "interview"],
  ["theWager", "067", "The Wager", "scorecard"],
  ["houseRules", "068", "House Rules", "steps"],
  ["categoryPillBar", "126", "Category Pill Bar", "pills"],
  ["heroPostGrid", "127", "Hero Post Grid (1 + 3)", "leadGrid"],
  ["latestFilmCarousel", "128", "Latest Film Carousel", "carousel"],
  ["featuredPostBand", "129", "Featured Post Band", "banner"],
  ["latestNewsThreeUp", "130", "Latest News Three-Up", "cards"],
  ["filterableArchive", "131", "Filterable Archive Grid", "archive"],
  ["subscribeCtaSplit", "132", "Subscribe CTA Split", "subscribe"],
  ["socialFollowStrip", "133", "Social Follow Strip", "social"],
  ["megaFooter", "134", "Mega Footer", "footer"],
  ["newsletterModal", "135", "Newsletter Modal", "modal"],
  ["contributorsRow", "136", "Contributors Row", "profile"],
  ["trendingTicker", "137", "Trending Ticker", "ticker"],
  ["listSidebar", "138", "List + Sidebar", "sidebar"],
  ["searchResults", "139", "Search Overlay Results", "search"],
  ["paginationLoadMore", "140", "Pagination / Load More", "pagination"],
  ["announcementBar", "141", "Announcement Bar", "announcement"],
  ["audioPodcastList", "142", "Audio / Podcast List", "audio"],
  ["topicCloud", "143", "Topic Cloud", "topics"],
  ["editorsLetter", "144", "Editor's Letter", "letter"],
  ["relatedReading", "145", "Related Reading Strip", "cards"],
] as const;

export type SectionStudioPreset = (typeof SECTION_STUDIO_PRESETS)[number];
export type SectionStudioVariant = SectionStudioPreset[0];
export type SectionStudioLayout = SectionStudioPreset[3];

export function sectionStudioPreset(value: SectionStudioVariant): SectionStudioPreset {
  return SECTION_STUDIO_PRESETS.find((preset) => preset[0] === value) ?? SECTION_STUDIO_PRESETS[0];
}
