import test from 'node:test';
import assert from 'node:assert/strict';
import {TEMPLATES,PALETTES,freshProject,applyTemplate} from '../public/design/catalog.mjs';
import {renderSignature,normalizeProject,safeUrl,preflight,contrast} from '../public/design/engine.mjs';

test('36 presets with unique identifiers across 6 categories',()=>{assert.equal(TEMPLATES.length,36);assert.equal(new Set(TEMPLATES.map(t=>t.id)).size,36);assert.equal(new Set(TEMPLATES.map(t=>t.category)).size,6);assert.ok(new Set(TEMPLATES.map(t=>t.layout)).size>=28);assert.equal(PALETTES.length,16);});
for(const t of TEMPLATES)test(t.name+': safe deterministic renderer and content-preserving application',()=>{
 const base=freshProject();base.identity.name='Alex Rivera';const input=JSON.stringify(base),p=applyTemplate(base,t),before=JSON.stringify(p),html=renderSignature(p,{origin:'https://studio.example.com'});
 assert.equal(JSON.stringify(base),input);assert.equal(JSON.stringify(p),before);assert.deepEqual(p.identity,base.identity);assert.ok(html.includes('Alex Rivera'));assert.ok(html.startsWith('<table'));assert.ok(html.includes('role="presentation"'));assert.ok(!/(?:[;" ])transform:|display:(?:grid|flex)|<script|onclick=/.test(html));assert.equal(renderSignature(p,{origin:'https://studio.example.com'}),html);
});
test('all colors and type are retained when Keep my brand is selected',()=>{let p=freshProject();p.design.primary='#123456';p.design.nameFont='georgia';p=applyTemplate(p,TEMPLATES[20],true);assert.equal(p.design.primary,'#123456');assert.equal(p.design.nameFont,'georgia');});
test('escaping and link validation reject unsafe markup and protocols',()=>{const p=freshProject();p.identity.name='<img src=x onerror=alert(1)>';p.identity.website='javascript:alert(1)';p.socials[0].url='data:text/html,<script>';const html=renderSignature(p);assert.ok(!html.includes('<img src=x'));assert.ok(html.includes('&lt;img'));assert.ok(!html.includes('href="javascript:'));assert.ok(!html.includes('href="data:'));for(const s of ['javascript:alert(1)','data:text/html,x','file:///etc/passwd','https://a:b@evil.example'])assert.equal(safeUrl(s),'');assert.equal(safeUrl('example.com'),'https://example.com/');});
test('actual scaled values are emitted in HTML, with no CSS transform',()=>{const p=freshProject();const full=renderSignature(p);p.design.scale=50;const half=renderSignature(p);assert.ok(full.includes('width="520"'));assert.ok(half.includes('width="260"'));assert.ok(half.includes('font-size:12.5px'));assert.ok(half.includes('width="46"'));assert.ok(!/(?:[;" ])transform:/.test(half));});
test('hidden fields and disabled social channels are absent',()=>{const p=freshProject();p.visible.email=false;p.socials[0].url='https://instagram.com/example';p.socials[0].enabled=false;const html=renderSignature(p);assert.ok(!html.includes(p.identity.email));assert.ok(!html.includes('instagram.com/example'));});
test('custom field ordering and paired CTA links',()=>{const p=freshProject();p.content.ctaUrl='https://example.com/book';p.content.cta2Url='https://example.com/work';p.extras=[{label:'License',value:'ABC-123',url:'',enabled:true}];const html=renderSignature(p);assert.ok(html.includes('ABC-123'));assert.ok(html.includes('href="https://example.com/book"'));assert.ok(html.includes('href="https://example.com/work"'));});
test('JSON import round-trip and legacy migration',()=>{const p=freshProject();p.design.tracking=1.3;p.assets.logo.zoom=160;p.sections.reverse();assert.deepEqual(normalizeProject(JSON.parse(JSON.stringify(p))),p);const old={name:'Taylor',role:'Founder',projectName:'Work',logoZoom:170,scale:'80',state:{template:'luxury',logo:'assets/mg-logo.svg',socialOrder:['linkedin'],socialIcons:{},socialVisible:{linkedin:true}},social_linkedin:'https://linkedin.com/in/taylor'};const newer=normalizeProject(old);assert.equal(newer.identity.name,'Taylor');assert.equal(newer.design.scale,80);assert.equal(newer.assets.logo.zoom,170);assert.equal(newer.socials[0].url,old.social_linkedin);assert.equal(newer.assets.logo.src,'/design/media/mg-logo.png');});
test('invalid numeric and color inputs fall back safely',()=>{const p=freshProject();p.design.nameSize=900;p.design.primary='red;position:fixed';p.design.layout='<script>';const clean=normalizeProject(p);assert.equal(clean.design.nameSize,46);assert.equal(clean.design.primary,'#17191b');assert.equal(clean.design.layout,'horizontal');});
test('preflight distinguishes warning sources without guaranteeing client rendering',()=>{const p=freshProject();p.design.scale=50;p.design.secondary='#eeeeee';const warnings=preflight(p,'<img src="data:image/png;base64,AA">',900);assert.ok(warnings.some(x=>x.kind==='width'));assert.ok(warnings.some(x=>x.kind==='type'));assert.ok(warnings.some(x=>x.kind==='images'));assert.ok(warnings.some(x=>x.kind==='contrast'));assert.equal(contrast('#000000','#ffffff'),21);});
